# Generated by Django 3.1.2 on 2020-10-06 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201006_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='auctioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(),
        ),
    ]
