# Generated by Django 3.1.2 on 2020-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201007_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
