# Generated by Django 3.1.2 on 2020-10-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201007_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='creation_date',
        ),
    ]
