# Generated by Django 3.1.2 on 2020-10-07 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 12, 31, 38, 199901, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
