# Generated by Django 3.1.2 on 2020-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.TextField()),
                ('articleimage', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photos', to='auctions.Photo'),
        ),
    ]
