# Generated by Django 3.1.2 on 2020-10-08 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201007_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='imagename',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='articleimage',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=datetime.datetime(2020, 10, 8, 8, 53, 17, 654053, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
