# Generated by Django 3.1.2 on 2020-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201008_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
