# Generated by Django 3.1.2 on 2020-10-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201008_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.TextField(),
        ),
    ]
