# Generated by Django 3.1.2 on 2020-10-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201008_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
