# Generated by Django 3.1.2 on 2020-10-08 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201008_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='../media'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_name',
            field=models.TextField(default=datetime.datetime(2020, 10, 8, 10, 15, 39, 567847, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.TextField(default=datetime.datetime(2020, 10, 8, 10, 15, 49, 598982, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
