# Generated by Django 3.1.2 on 2020-10-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201008_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='photos',
        ),
        migrations.AddField(
            model_name='auction',
            name='photos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auctions.photo'),
            preserve_default=False,
        ),
    ]
