# Generated by Django 3.1.2 on 2020-10-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201008_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='photos',
            new_name='photo',
        ),
    ]
