# Generated by Django 3.1.2 on 2020-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201008_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='photo',
        ),
        migrations.AddField(
            model_name='auction',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='auctions.Photo'),
        ),
    ]
