# Generated by Django 3.1.2 on 2020-10-09 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20201008_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whish_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whish_auction', to='auctions.auction')),
                ('whish_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whish_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
