# Generated by Django 3.1.2 on 2020-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201009_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Auction'),
        ),
    ]
