# Generated by Django 3.1.2 on 2020-10-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auction_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='creator',
        ),
    ]
