# Generated by Django 3.1.2 on 2020-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auction_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
