# Generated by Django 3.1.2 on 2020-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20201019_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.CharField(max_length=64),
        ),
    ]
