# Generated by Django 3.1.2 on 2020-10-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20201019_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
