# Generated by Django 3.1.2 on 2020-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20201019_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
