# Generated by Django 3.1.2 on 2020-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_auto_20201019_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
