# Generated by Django 3.1.2 on 2020-10-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20201019_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
    ]
