# Generated by Django 3.1.2 on 2020-12-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auction_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='describtion',
            new_name='description',
        ),
    ]
